# Generated by Django 3.1.5 on 2021-01-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0002_auto_20210109_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='plants',
        ),
        migrations.CreateModel(
            name='OrderPlantProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='nursery.order')),
            ],
        ),
    ]
