# Generated by Django 3.1.5 on 2021-01-09 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0004_auto_20210109_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproperty',
            name='plant',
        ),
        migrations.AddField(
            model_name='orderproperty',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nursery.plant'),
            preserve_default=False,
        ),
    ]
