# Generated by Django 3.1.5 on 2021-01-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0007_auto_20210109_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursery',
            name='name',
        ),
    ]
