# Generated by Django 3.1.5 on 2021-01-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0008_remove_nursery_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nursery',
            old_name='owner',
            new_name='nursery',
        ),
    ]
