# Generated by Django 3.1.5 on 2021-01-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0009_auto_20210109_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nursery',
            old_name='nursery',
            new_name='owner',
        ),
    ]
