# Generated by Django 3.1.5 on 2021-01-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0010_auto_20210109_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nursery',
            old_name='owner',
            new_name='name',
        ),
    ]
