# Generated by Django 3.1.5 on 2021-01-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0011_auto_20210109_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nursery',
            old_name='name',
            new_name='owner',
        ),
    ]
